include ../../make_env.mk

# Vivado variables (user-defined)
export VIVADO_PROJ_NAME := subtractor
export VIVADO_VENDOR := niiichtsy
export VIVADO_LIBRARY := hardwell

# Core version 
export VERSION := 1.0

# IP library paths
# IP_LIBRARY_PATH := ip/

# Library dependecies
# LIB_DEPS +=
