include ../../make_env.mk

# Vivado variables (user-defined)
export VIVADO_PROJ_NAME := adder
export VIVADO_VENDOR := niiichtsy
export VIVADO_LIBRARY := hardwell

# Core version 
export VERSION := 1.0

# IP library paths
export IP_LIBRARY_PATH :=

# Library dependecies
export IP_LIST := 
