include ../../make_env.mk

# Vivado variables (user-defined)
export VIVADO_PROJ_NAME := eth_pkt_gen
export VIVADO_VENDOR := niiichtsy
export VIVADO_LIBRARY := hardwell

# Core version 
export VERSION := 1.0

# IP library paths
UTIL_LIBRARY_PATH := $(ROOT_DIR)/utils/
export IP_LIBRARY_PATH := $(UTIL_LIBRARY_PATH) 

# Library dependecies
UTIL_LIST += lfsr
export IP_LIST := $(UTIL_LIST)

