include ../make_env.mk

# Vivado variables (user-defined)
VIV_DESIGN = clk_divider
export VIVADO_PROJ_NAME := $(VIV_PROD_DIR)
export VIVADO_VENDOR := niiichtsy
export VIVADO_LIBRARY := verilog_misc_modules

# IP library paths
# IP_LIBRARY_PATH := ip/

# Library dependecies
# LIB_DEPS +=
